import type { Metadata } from "next";
import { AuthProvider } from "@/components/auth-provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {/* 背景网格装饰 */}
        <div
          className="fixed inset-0 z-0 pointer-events-none opacity-[0.03] breath-bg"
          style={{
            backgroundImage: "linear-gradient(currentColor 1px, transparent 1px), linear-gradient(90deg, currentColor 1px, transparent 1px)",
            backgroundSize: "40px 40px",
          }}
        ></div>

        <AuthProvider>
          <div className="relative z-10 flex-1 flex flex-col max-w-5xl mx-auto w-full px-3 md:px-6 py-8 md:py-10">{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
